Repository knative-extensions/eventing-natss, pull requests merged in 2020-10, with the labels that each got.

#21 use utils in knative/pkg
  pkg/reconciler/controller/natsschannel_test.go
  pkg/reconciler/controller/resources/service.go
  pkg/util/util.go
Labels: approved, cla: yes, lgtm, size/S

#19 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/constants.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/test/lib/duck/resource_inspectors.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/helpers/dryrun.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/mako/config/environment.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#20 [Automated] Update actions
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#24 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#29 leverage new test-infra go_update_deps
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/golang.org/x/tools/go/analysis/validate.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#30 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#31 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/messaging/v1beta1/natsschannel/reconciler.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/resources/variables.go
  vendor/knative.dev/eventing/test/lib/typemeta.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/mako/config/configmap.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#32 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/channel/metrics.go
  vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
  vendor/knative.dev/eventing/pkg/kncloudevents/utils.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/flags/e2e_flags.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#34 Removed deprecated test images
  hack/tools.go
  vendor/knative.dev/eventing/test/test_images/filterevents/main.go
  vendor/knative.dev/eventing/test/test_images/filterevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sequencestepper/main.go
  vendor/knative.dev/eventing/test/test_images/sequencestepper/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#35 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#36 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#37 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#38 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#40 fix compilation, create reporters
  config/500-controller.yaml
  config/500-dispatcher.yaml
  go.mod
  pkg/dispatcher/dispatcher.go
  pkg/reconciler/dispatcher/natsschannel.go
  pkg/reconciler/dispatcher/natsschannel_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#43 fix CONTAINER_NAME env indent
  config/500-dispatcher.yaml
Labels: approved, cla: yes, lgtm, size/XS

#44 Use the network.GetServiceHostname helper
  pkg/reconciler/controller/natsschannel.go
  pkg/reconciler/controller/natsschannel_test.go
  pkg/reconciler/controller/resources/service.go
  pkg/reconciler/controller/resources/service_test.go
  vendor/knative.dev/eventing/pkg/reconciler/names/mtbroker.go
  vendor/knative.dev/eventing/pkg/reconciler/names/names.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#42 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#45 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/fuzzer.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/dropevents/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/logger_vent/logger.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#46 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#50 [release-0.18] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/messaging/v1alpha1/natsschannel/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
