Repository knative-extensions/eventing-natss, pull requests merged in 2021-06, with the labels that each got.

#153 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#152 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#154 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#160 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#161 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/performance/infra/image_helpers.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#159 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#163 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#165 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#166 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#168 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#170 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/api_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/feature/store.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/recorder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#169 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#172 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#174 Fix Kinda #173
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#175 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#176 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS
