Repository knative-extensions/eventing-natss, pull requests merged in 2021-02, with the labels that each got.

#94 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#96 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#95 Remove @Harwayne from OWNERS.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#97 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/pmezard/go-difflib/difflib/LICENSE
  third_party/VENDOR-LICENSE/github.com/stretchr/testify/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/NOTICE
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/step.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#98 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#99 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#100 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#101 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#102 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#103 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#104 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#106 update deps for 0.21
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#105 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
