Repository knative-extensions/eventing-natss, pull requests merged in 2021-12, with the labels that each got.

#273 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#272 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#274 Fix rekt compile errors
  go.mod
  go.sum
  test/e2e/direct_test.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#276 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#277 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#278 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved

#279 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#280 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_composite.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_log.go
  vendor/knative.dev/reconciler-test/pkg/milestone/factory.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#281 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved
