Repository knative-extensions/eventing-natss, pull requests merged in 2021-11, with the labels that each got.

#261 Document maturity levels in sandbox
  README.md
Labels: cla: yes, size/XS, lgtm, approved

#260 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#262 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#264 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, lgtm, approved

#266 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#265 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, size/M, approved

#271 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/XS, lgtm, approved

#268 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/eventing/pkg/utils/headers.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/XL, approved

#270 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved
