Repository knative-extensions/eventing-natss, pull requests merged in 2022-08, with the labels that each got.

#351 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/M, skip-review

#352 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#353 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#354 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#355 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#349 applied tracing propagation for eventing 1.3.x release version
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-style.yaml
  go.mod
  pkg/dispatcher/natss_dispatcher.go
  pkg/reconciler/dispatcher/natss/natsschannel.go
  pkg/reconciler/dispatcher/natss/natsschannel_test.go
  pkg/tracing/tracing.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#357 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#358 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
