Repository knative-extensions/eventing-natss, pull requests merged in 2022-04, with the labels that each got.

#310 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved

#311 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, size/L, approved

#313 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#312 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#316 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#317 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#318 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#315 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#302 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: lgtm, size/M, approved

#320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#321 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#324 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
