Repository knative-extensions/eventing-natss, pull requests merged in 2022-03, with the labels that each got.

#292 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#290 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: lgtm, size/M, approved

#293 Remove k8s 1.20 from the test matrix
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#294 Removed k8s < 1.21 from workflows
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#295 fix OOM when building the release in prow
  hack/release.sh
Labels: size/XS, lgtm, approved

#296 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#297 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#299 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#300 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#304 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#306 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/reconciler-test/pkg/feature/steps.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#305 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, size/XL, approved

#307 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/modules.txt
Labels: lgtm, size/M, approved

#309 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#308 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved
