Repository knative-extensions/eventing-natss, pull requests merged in 2022-09, with the labels that each got.

#359 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#360 Bugfix release-1.3 process
  hack/release.sh
  hack/vendor-library.sh
  hack/vendor-release.sh
Labels: lgtm, size/XXL, approved

#361 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#367 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#365 jsm tracing propagation fixed release-1.3.x
  pkg/dispatcher/jetstream_dispatcher.go
  pkg/dispatcher/natss_dispatcher.go
  pkg/reconciler/dispatcher/jetstream/nats_jetstreaming_schannel.go
  pkg/tracing/tracing.go
  pkg/tracing/tracing_test.go
Labels: lgtm, size/L, approved

#368 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/messaging/v1alpha1/natsjetstreamchannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/natsschannel/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#370 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#369 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#371 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
