Repository knative-extensions/eventing-natss, pull requests merged in 2023-07, with the labels that each got.

#410 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#413 Upgrade e2e tests to eventing v1.10.1
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#412 Upgrade kind to Kubernetes v1.25.3
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#408 added connection and retry options for jsm client
  docs/jetstream.md
  examples/config-br-default-channel-jsm.yaml
  examples/config-nats.yaml
  pkg/common/config/eventingnatsconfig.go
  pkg/common/nats/conn.go
Labels: lgtm, size/M, approved

#409 implemented reconnects for jetstream channels
  docs/jetstream.md
  examples/config-br-default-channel-jsm.yaml
  examples/config-nats.yaml
  pkg/common/config/eventingnatsconfig.go
  pkg/common/nats/conn.go
Labels: lgtm, size/M, approved

#414 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#415 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
  vendor/knative.dev/eventing/pkg/eventtype/eventtypes.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#416 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventtype/eventtypes.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: lgtm, size/L, approved
