Repository knative-extensions/eventing-natss, pull requests merged in 2023-11, with the labels that each got.

#452 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#455 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#458 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#459 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#460 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#461 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, lgtm, approved

#462 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v3/jwt/builder.go
  vendor/github.com/go-jose/go-jose/v3/jwt/claims.go
  vendor/github.com/go-jose/go-jose/v3/jwt/doc.go
  vendor/github.com/go-jose/go-jose/v3/jwt/errors.go
  vendor/github.com/go-jose/go-jose/v3/jwt/jwt.go
  vendor/github.com/go-jose/go-jose/v3/jwt/validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/auth/token_provider.go
  vendor/knative.dev/eventing/pkg/auth/utils.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/state/timings.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#463 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#465 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#466 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_event_handler.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#468 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#469 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/modules.txt
Labels: lgtm, size/M, approved
