Repository knative-extensions/eventing-natss, pull requests merged in 2024-01, with the labels that each got.

#480 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#483 chore: backport OWNERS_ALIASES to release-1.10
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#484 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/105-certificate-service.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/resources/secret/secret.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#486 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/messaging/v1alpha1/natsjetstreamchannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/natsschannel/reconciler.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#488 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#467 reconnect jitter configurable
  docs/jetstream.md
  examples/config-nats.yaml
  pkg/common/config/eventingnatsconfig.go
  pkg/common/nats/conn.go
Labels: lgtm, size/M, approved

#490 Bump k8s to 1.27 in kind tests
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#491 bump knative version to v1.12 in the kind tests
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#494 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#497 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#498 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#500 Update to Golang 1.21
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
Labels: size/S, lgtm, approved

#499 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/knative.dev/eventing/pkg/channel/event_receiver.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_event_handler.go
  vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
  vendor/knative.dev/eventing/pkg/metrics/metrics.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#501 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#503 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/modules.txt
Labels: lgtm, size/M, approved
