Repository knative-extensions/eventing-natss, pull requests merged in 2024-10, with the labels that each got.

#606 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_types.go
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#608 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#609 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#610 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#611 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#614 fixed wrong dispatcher permissions
  config/jetstream/200-jsm-dispatcher-clusterrole.yaml
Labels: lgtm, size/M, approved

#612 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#615 Remove deprecated yaml from release script
  hack/release.sh
Labels: size/XS, lgtm, approved

#617 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#618 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta3/eventtype.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta3/expansion_generated.go
  vendor/knative.dev/eventing/pkg/eventtype/eventtypes.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#619 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventtype/eventtypes.go
  vendor/modules.txt
Labels: size/S, lgtm, approved
