Repository knative-extensions/eventing-natss, pull requests merged in 2024-05, with the labels that each got.

#554 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#555 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/LICENSE
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/compute/metadata/CHANGES.md
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/compute/metadata/retry.go
  vendor/cloud.google.com/go/compute/metadata/tidyfix.go
  vendor/github.com/klauspost/compress/internal/race/norace.go
  vendor/github.com/klauspost/compress/internal/race/race.go
  vendor/github.com/klauspost/compress/s2/decode.go
  vendor/github.com/klauspost/compress/s2/dict.go
  vendor/github.com/klauspost/compress/s2/encode.go
  vendor/github.com/klauspost/compress/s2/encode_all.go
  vendor/github.com/klauspost/compress/s2/encode_amd64.go
  vendor/github.com/klauspost/compress/s2/encode_best.go
  vendor/github.com/klauspost/compress/s2/encode_go.go
  vendor/github.com/klauspost/compress/s2/encodeblock_amd64.s
  vendor/github.com/klauspost/compress/s2/index.go
  vendor/github.com/klauspost/compress/s2/reader.go
  vendor/github.com/klauspost/compress/s2/s2.go
  vendor/github.com/klauspost/compress/s2/writer.go
  vendor/github.com/openzipkin/zipkin-go/.golangci.yml
  vendor/github.com/openzipkin/zipkin-go/README.md
  vendor/github.com/openzipkin/zipkin-go/SECURITY.md
  vendor/github.com/openzipkin/zipkin-go/span_implementation.go
  vendor/github.com/openzipkin/zipkin-go/span_options.go
  vendor/github.com/prometheus/common/model/alert.go
  vendor/github.com/prometheus/common/model/labelset_string.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscribable_channelable_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_event_handler.go
  vendor/knative.dev/eventing/pkg/crossnamespace/validation.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/images/ko/publish.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#556 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#558 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#557 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/encoding/tag/tag.go
  vendor/google.golang.org/protobuf/internal/errors/errors.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/placeholder.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_enum.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_extension.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_file.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/messageset.go
  vendor/google.golang.org/protobuf/proto/size.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#545 re-applied backport pkg files from release-1.10
  go.mod
  pkg/channel/jetstream/dispatcher/consumer.go
  pkg/channel/jetstream/dispatcher/defaults.go
  pkg/channel/jetstream/dispatcher/dispatcher.go
  pkg/channel/jetstream/dispatcher/dispatcher_test.go
  pkg/channel/jetstream/dispatcher/message_dispatcher.go
  pkg/channel/jetstream/dispatcher/message_dispatcher_test.go
  pkg/channel/jetstream/utils/consumerconfig.go
  pkg/reconciler/testing/natsjetstreamchannel.go
Labels: lgtm, size/XXL, approved

#560 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#562 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/crossnamespace/validation.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#566 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, skip-review

#568 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#569 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_conversion.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: lgtm, size/L, approved
