Repository knative-extensions/eventing-natss, pull requests merged in 2024-04, with the labels that each got.

#535 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#536 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#537 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#538 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/acks_before_finish_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/binary_buffer_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/copy_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/struct_buffer_message.go
  vendor/github.com/valyala/bytebufferpool/.travis.yml
  vendor/github.com/valyala/bytebufferpool/LICENSE
  vendor/github.com/valyala/bytebufferpool/README.md
  vendor/github.com/valyala/bytebufferpool/bytebuffer.go
  vendor/github.com/valyala/bytebufferpool/doc.go
  vendor/github.com/valyala/bytebufferpool/pool.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/channel/fanout/fanout_event_handler.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#539 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#527 fixed case when no deliver configuration in subscription
  pkg/channel/jetstream/dispatcher/dispatcher_test.go
  pkg/channel/jetstream/dispatcher/message_dispatcher.go
  pkg/channel/jetstream/dispatcher/message_dispatcher_test.go
Labels: lgtm, size/L, approved

#540 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#547 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#548 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#550 fix: add .spec.subscribers[].name field in NATSS channel to align with eventing core
  config/jetstream/302-jsm-channel.yaml
Labels: size/XS, lgtm, approved

#551 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#552 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#553 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
