Repository knative-extensions/eventing-natss, pull requests merged in 2025-09, with the labels that each got.

#678 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, skip-review

#683 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/images/ko/publish.go
  vendor/modules.txt
Labels: size/S, skip-review

#688 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/time.go
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/gotrack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/unix/affinity_linux.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/packages/visit.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/go/types/typeutil/map.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport_go122.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/modules.txt
Labels: size/XXL, skip-review

#689 removed patching of ophaned subs from CRD status
  pkg/channel/jetstream/dispatcher/reconciler.go
Labels: size/S, lgtm, approved

#692 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/event_receiver.go
  vendor/knative.dev/eventing/pkg/channel/references.go
  vendor/modules.txt
Labels: size/S, skip-review
