Repository knative-extensions/eventing-natss, pull requests merged in 2025-08, with the labels that each got.

#663 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/internal/difflib.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_nocgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_procfsenabled.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bool_func.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/errors.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/func.go
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/text.go
  vendor/github.com/spf13/pflag/time.go
  vendor/golang.org/x/crypto/blake2b/blake2x.go
  vendor/golang.org/x/crypto/blake2b/go125.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/internal/modindex/lookup.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#664 cleanup: drop the usage of pkg/tracing
  pkg/channel/jetstream/dispatcher/controller.go
Labels: size/XS, lgtm, approved

#666 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, do-not-merge/hold, skip-review

#672 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/observability/config.go
  vendor/modules.txt
Labels: size/S, skip-review

#674 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, skip-review

#676 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/integration_sink_types.go
  vendor/modules.txt
Labels: size/S, skip-review
