Repository knative-extensions/eventing-natss, pull requests merged in 2025-01, with the labels that each got.

#625 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/knative.dev/eventing/pkg/apis/common/integration/v1alpha1/aws.go
  vendor/knative.dev/eventing/pkg/apis/common/integration/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/requestreply_defaults.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/integration_sink_types.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/integration_sink_validation.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_types.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/integration_validation.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, size/L, approved

#629 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#628 removed wrong ns from readme
  config/broker/README.md
Labels: size/XS, lgtm, approved

#632 increased k8s version for e2e tests
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#631 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#634 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#636 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
